name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: 'central'
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Set Git User Identity
      run: |
        git config --local user.email shitikanth1@gmail.com
        git config --local user.name "Shitikanth Kashyap"
    - name: Perform Release
      run: ./mvnw -B -Prelease release:prepare release:perform -Dgpg.signer=bc
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}